services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=CAMBIA_ROOT_DB
      - MARIADB_DATABASE=prestashop
      - MARIADB_USER=prestashop
      - MARIADB_PASSWORD=CAMBIA_DB_PASS
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - prestashop_db_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - DB_SERVER=mariadb
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=CAMBIA_DB_PASS
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=dawaa3-prestashop-XXXXXX-212-227-134-220.traefik.me
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - PS_ENABLE_SSL=0
      - ADMIN_MAIL=tu-correo@dominio.com
      - ADMIN_PASSWD=CAMBIA_ADMIN_PASS
      - PS_FOLDER_ADMIN=admin123
      - PS_FOLDER_INSTALL=install123
    volumes:
      - prestashop_data:/var/www/html

volumes:
  prestashop_db_data:
  prestashop_data:
